apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: insights-prometheus-rules
  namespace: openshift-insights
spec:
  groups:
  - name: insights
    rules:
    - alert: InsightsDisabled
      annotations:
        description: 'Insights operator is disabled. In order to enable Insights and benefit from recommendations specific to your cluster, please follow steps listed in the documentation: https://docs.openshift.com/container-platform/latest/support/remote_health_monitoring/enabling-remote-health-reporting.html'
        summary: Insights operator is disabled.
      expr: |
       cluster_operator_conditions{name="insights", condition="Disabled"} == 1
      for: 5m
      labels:
        severity: info
        